From zero to hero: Static World (part 1)
dqrobotics/learning-dqrobotics-with-coppeliasim pull request #3
Opened 2024-06-19 12:41 UTC by ffasilva

Hi @dqrobotics/developers,

I've added the draft of the second lesson of the crash course "CoppeliaSim interface with DQ Robotics: From zero to hero." Let me know what you think of it.

Kind regards,
Frederico

2024-06-20 17:06 UTC, mmmarinho commented
Hi @bvadorno and @ffasilva,

it seems we all agree so it’s public now.

2024-06-23 16:50 UTC, bvadorno requested changes

2024-07-22 15:50 UTC, ffasilva commented on lesson2/lesson_2_static_world_part_1.mlx
Hi @bvadorno,

Thank you for the comments.

> 1. Please adjust the license according to my comments in Lesson 1.

Adjusted in [b443a74](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/b443a740f20a61fbba7703c30aed3438101d98da).

>     2. Please use Grammarly or another grammar tool to check the grammar. There are some typos and grammar mistakes. A common mistake you are making is confusing `it's` with `its`.

Text revised in [1ff4898](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/1ff489851afcd3d58a51500c60607d85b7ac7191).

>     3. Include some references on how to configure the communication on CoppeliaSim. Here, you assume that users know that you are using the remoteAPI, which will rarely be true, especially for the inexperienced. I already added some information on our [wiki](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/wiki/Tips-and-Tricks), but it will benefit from a more step-by-step, visual description in the [MacOS section](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/wiki/Tips-and-Tricks#instructions-for-macos-users), similarly to [here](https://github.com/dqrobotics/matlab/blob/master/CONTRIBUTING.md#fork-the-dqroboticsmatlab-in-your-github-account).

Environment setup explanation add in [ca801b5](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/ca801b53ef3324a06da3615726d13ff179a15229).

>     4. Do we need the third argument in `vi.get_object_pose('/Cup','/LBR4p/connection', vi.OP_BLOCKING)`? If so, please add an explanation for it. Otherwise, omit it.

Unfortunately we do. I would expect to be possible to have

`vi.get_object_pose('/Cup','/LBR4p/connection')`

but the current implementation only allows to either

`vi.get_object_pose('/Cup')`

or

`vi.get_object_pose('/Cup','/LBR4p/connection', vi.OP_BLOCKING)`

I added a explanation on the third argument in [71652d8](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/71652d811848d4301b098911f7956d2150051036).

>     5. Please add a better, more pedagogical explanation of how you are referencing each element in the scene.

I'm not sure what you mean here. I added an extra step explaining how an object alias is found in [e570967](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/e57096771e578054104e76c2eaae9a8d400c1175).

> Please change
> 
> > `Similarly to the use of 'Object/item shift' and 'Object/item rotate',
> 
> to
> 
> > `Similarly to the menu buttons 'Object/item shift' and 'Object/item rotate',

Also changed in [1ff4898](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/1ff489851afcd3d58a51500c60607d85b7ac7191).

Please let me know if there is still something missing.

Kind regards,
Frederico

2025-08-25 11:21 UTC, bvadorno commented
Hi @ffasilva and @juanjqo,

Thanks for bringing this one to light again. @juanjqo, are you happy with the current modifications? 

Kind regards,
Bruno

2025-08-26 09:51 UTC, bvadorno commented
@ffasilva, please see my latest comment on Lesson 1: https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/2/files#r1649770728

Kind regards,
Bruno

2025-08-29 10:48 UTC, bvadorno commented on lesson2/lesson_2_static_world_part_1.mlx
@ffasilva, please see Juancho's and my comments above.

> However, I believe there is some missing step in the information from the [Wiki](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/wiki/Tips-and-Tricks) for MacOS. If I try to follow this step
> 
> > Make sure to have the server side running in CoppeliaSim. In a child script of a CoppeliaSim scene, add the following command to be executed just once, at simulation start:
> > `simRemoteApi.start(19997, 1300, false, true)`
> 
> I get the error `attempt to index a nil value (global 'simRemoteApi')` in CoppeliaSim when I try to run the scene. Google didn't help me too much here.

I've just followed the instructions from scratch, and it worked. I'm using CoppeliaSim Edu, Version 4.5.1 (rev. 4), MacOS Sequoia 15.6 on a 16-inch 2019 Macbook Pro, with MATLAB R2023a. Therefore, I conclude that there are no missing steps, at least for the configuration I'm using. Assuming you have followed all steps strictly, maybe it has to do with the version of each software you are using? How did you solve the problem on your end?

> I'm not sure what you mean here. I added an extra step explaining how an object alias is found in [e570967](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/e57096771e578054104e76c2eaae9a8d400c1175).

I mean that the explanation wasn't good enough. The updated version is fine, though. Thanks.

We're almost there. After you fulfil Juancho's requests and take into consideration what I mentioned [here](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3#issuecomment-3223463862), I'll approve this merge.

Kind regards,
Bruno

2025-08-29 13:59 UTC, ffasilva commented
Hi @juanjqo,

> I have some minor comments (I am unsure how to review MLX files properly. Therefore, I saved it as an M-file to extract the line numbers and facilitate the process):
    [L45] In the Environment setup section, the DQ_VrepInterface class is still used.
    In addition to the DQ_CoppeliaSimInterface and ZMQ remote API classes, the DQ_CoppeliaSimInterfaceZMQ class is also required. (We could add this step to the instructions.)
    [L55] it is written DQ_Robotic instead of DQ_Robotics
    [L68] it is written stablish instead of establish
    [L107-L104] The DQ_VrepInterface class is still used.
    [L124] the DQ_VrepInterface class is still used.
    [L140] the DQ_VrepInterface class is still used.

I've fixed those points in [bd66552](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/commits/bd66552a85df901d46cc2c7a7c63490a24122603).

> @ffasilva is the static_world.ttt scene available in some repository? (if not, I think we could have it in [coppeliasim-scenes](https://github.com/dqrobotics/coppeliasim-scenes))

As explained in the [README.md](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/blob/main/README.md#how-to-use), the scenes are available on OSF, as we [agreed at the time](https://github.com/dqrobotics/coppeliasim-scenes/pull/1#issuecomment-2704544446). I have no preference whether to keep them there or move them to [coppeliasim-scenes](https://github.com/dqrobotics/coppeliasim-scenes).

Kind regards,
Frederico

2025-08-29 14:07 UTC, ffasilva commented
Hi @bvadorno,

> @ffasilva, please see my latest comment on Lesson 1: https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/2/files#r1649770728
Important
I decided to merge lesson 1. However, my comments above still hold, and we should refer to either a specific commit in the master branch or a particular release version.

I'll review this point and make a new pull request to fix the [README.md](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/blob/main/README.md#how-to-use). Since the [interface with CoppeliaSim](https://github.com/dqrobotics/matlab-interface-coppeliasim-zmq) is no longer part of [matlab](https://github.com/dqrobotics/matlab), everything should work with the realise version of [matlab](https://github.com/dqrobotics/matlab).

Kind regards,
Frederico

2025-08-29 14:38 UTC, ffasilva commented on lesson2/lesson_2_static_world_part_1.mlx
> I've just followed the instructions from scratch, and it worked. I'm using CoppeliaSim Edu, Version 4.5.1 (rev. 4), MacOS Sequoia 15.6 on a 16-inch 2019 Macbook Pro, with MATLAB R2023a. Therefore, I conclude that there are no missing steps, at least for the configuration I'm using. Assuming you have followed all steps strictly, maybe it has to do with the version of each software you are using? How did you solve the problem on your end?

It could have been related to the version of some software I was using, and I think I didn't manage to fix it at the time. However, this step is no longer necessary with the ZMQ interface. The [static_world.ttt](https://osf.io/2tfsx/files/osfstorage) doesn't have the line `simRemoteApi.start(19997, 1300, false, true)` in any child script, and [lesson_2_static_world_part_1.mlx](https://github.com/dqrobotics/learning-dqrobotics-with-coppeliasim/pull/3/files#diff-9a9a618cfc7c26f3cfc349b108c76a65eb72f9ac10a688f0192aadd8449fa416) is working on my Mac.

Kind regards,
Frederico

2025-08-29 15:08 UTC, merged

2025-08-29 15:09 UTC, bvadorno commented
@ffasilva, please see @juanjqo's and my comments above.